### PR TITLE
Specifiy batik version

### PR DESCRIPTION
**Pull request by physikerwelt**
The latest version batik 1.8 did not work for me.

### CODE REVIEW

**Comment by pkra** [comment]
See my comments on #81.

**Comment by dpvc** [comment]
I think mentioning the symbolic link option might be a better solution to the 1.8 problem.

**Comment by physikerwelt** [comment]
OK it works on linux... but windows does not support symlinks.
Feel free to regard this pull request as short bug report... so you probably don't want to merge it.

**Comment by physikerwelt** [comment]
Even in the new version png generation is extremly slow
´´´
 time ./tex2png 'E=mc^2' > ~/test.png

real    0m3.421s
user    0m2.929s
sys     0m0.172s
´´´

**Comment by pkra** [comment]
@physikerwelt do you happen to have any comparable data, e.g., using svg2png?

**Pull request closed without merging**
