### PR TITLE
Release 0.3

### LINKED ISSUE #85: missing MathEvents extension
It looks like #82 and the re-opened #66 are due to the MathEvents extension having been stripped from the slimmed-down copy of core MathJax.

@dpvc should I just add it back to the upstream mathjax-node branch or is this worth investigating?

### PR DESCRIPTION
**Pull request by pkra**
Are we good to go? E.g., #64 seems fixed now.

Also fixes #85, #82, #70, #62, #31

### CODE REVIEW

**Comment by dpvc** [comment]
I was planning to make the pull request myself, but was out of town all day yesterday.  When I was putting the final touches on things, I checked to see what version jsdom is at, since we have a fixed version in the `package.json` file; they are now at 3.1.1, and I thought I'd see if MathJax-node would work with that.  It turns out that something is not working (it says it can't find the MathJax.js file, but the URL is correct, and the same one that works in 1.0.2, so something else has changed.  I'm not sure if they implemented some form of same-origin policy, or added restrictions on file:// URL's or what, but I haven't been able to track it down yet.  I thought if was an easy fix, we could update, but it looks like it is going to be harder.  I do want to make one more change before merging the branch, but that should be soon.

**Comment by dpvc** [comment]
OK, I think this is ready to go.  I've tested in Windows and MacOS.  Shall we merge and tag a release?

**Comment by dpvc** [comment]
Alternatively, we could wait for the CLA for the last couple of pull requests, which look good.

**Comment by pkra** [comment]
I'm ok with waiting for the CLA a bit (since I made everyone wait a bit while being away).

**Comment by physikerwelt** [comment]
@pkra Is there still a problem with this pull request?

**Comment by Rycochet** [comment]
I've been using the develop branch (ie, the soon-to-be 0.3) in production for a couple of weeks now - so could this get a proper npm install too when merged?

**Comment by physikerwelt** [comment]
@Rycochet you can specify the branch in the npm dependency (cf https://github.com/physikerwelt/mathoid-server/blob/master/package.json#L54)

**Comment by pkra** [comment]
@physikerwelt CLA is in the process and it's worth our time to wait for it.

**Comment by Rycochet** [comment]
@physikerwelt I was meaning on npmjs btw - https://www.npmjs.com/ - would mean it's as simple as "npm install mathjax-node" to get this installed, rather than requiring a full url ;-)

**Comment by pkra** [comment]
@Rycochet this is the plan once 0.3 is done; see https://github.com/mathjax/MathJax-node/issues/64

**Comment by dpvc** [comment]
@pkra, if we haven't gotten the CLA for the last few pull requests, I think we should move ahead with this one, as I'd like to see v2.5 be available.

**Comment by dpvc** [comment]
PS, it would also help to update the MathJax-node-2.5 branch of MathJax to include the 2.5.1 changes.

**Comment by pkra** [comment]
@dpvc the CLA is almost ready (it was much more complex this time). We should be ready today or tomorrow.

I'll update the mathjax-node branch.

**Comment by pkra** [comment]
Actually, update or create new 2.5.1 branch?

**Comment by dpvc** [comment]
I guess you can make `MathJax-node-2.5.1` and change the pointer in the json file.  We haven't had an official version of MathJax-node that uses the `MathJax-node-2.5`, so I don't see a need to keep it, do you?

**Comment by pkra** [comment]
CLA is all set.

**Comment by pkra** [comment]
By which I means the CLA for @sammarshallou.

**Comment by pkra** [comment]
Ok, new mathjax-node branch is ready. Since it's hard to compare the branches:

```bash
$ git diff --name-status mathjax-node-2.5..mathjax-node-2.5.1
M       package.json
M       unpacked/MathJax.js
D       unpacked/extensions/CHTML-preview.js
D       unpacked/extensions/FontWarnings.js
D       unpacked/extensions/HTML-CSS/handle-floats.js
D       unpacked/extensions/HelpDialog.js
D       unpacked/extensions/MatchWebFonts.js
D       unpacked/extensions/MathEvents.js
M       unpacked/extensions/MathML/mml3.js
D       unpacked/extensions/MathMenu.js
D       unpacked/extensions/MathZoom.js
D       unpacked/extensions/Safe.js
M       unpacked/extensions/TeX/AMSmath.js
M       unpacked/extensions/TeX/mathchoice.js
M       unpacked/extensions/TeX/noErrors.js
M       unpacked/extensions/TeX/unicode.js
M       unpacked/jax/element/mml/jax.js
M       unpacked/jax/output/NativeMML/config.js
M       unpacked/jax/output/NativeMML/jax.js
```

**Comment by pkra** [comment]
I've updated package.json in the develop branch to use the new MathJax branch.

**Comment by dpvc** [comment]
OK, great.  I'll merge the pulls from @sammarshallou and then check that everything is in order, and then we can merge this pull.

**Comment by physikerwelt** [comment]
@Rycochet You are right... a npm package would be nice. I can not build the mathoid debian package from source without a proper npm package. ppa complains that it is not allowed to fetch npm packages from github

**Comment by pkra** [comment]
The MathJax branch has been updated and I've merged in the MathEvents fix.

**Comment by pkra** [comment]
Updated readme and batik readme.

**Pull request merged**
