### PR TITLE
Separate entry points for single and page.

### PR DESCRIPTION
**Pull request by kintesh**
Provides two separate entry points for single and page.

### CODE REVIEW

**Comment by pkra** [comment]
I like the idea (though the PR should be to `develop`, not `master`). @dpvc what do you think?

**Comment by kintesh** [comment]
My bad. delete this pull request, I'll make another one.

**Comment by dpvc** [comment]
I'm not certain that there doesn't have to be more work done to keep the two versions separate.  They don't currently isolate their global variables, so it may be that loading the two causes conflicts.  I haven't tried it out, but it may require compartmentalizing the two library files.  That is something that should be done, but may want to be part of rethinking the API now that we have a better idea of how it is going to be used.  (We talked about this some time ago.)

**Comment by pkra** [comment]
This fell of the radar.

a) it can't be merged anymore. 
b) it's aimed at master, not develop.

It would be great to restart the conversation though.

**Pull request closed without merging**
