### PR TITLE
[main] add option for returning dom objects

### LINKED ISSUE #219: return an object not a serialization
To separate this out from #205. 

As a developer, I want to post-process the results from mathjax-node which is easier to do with a DOM-like object rather than a string.

The problem is to find a reasonably universal, DOM-like object format in nodejs-land. Right now we're stuck with jsdom anyway which, I think, means parse5.

### PR DESCRIPTION
**Pull request by pkra**
Fixes #219.

### CODE REVIEW

**Comment by pkra** [comment]
A slightly different approach to @zorkow's in #250. 

PTAL.

**Comment by dpvc** [comment]
Note that the `*Element` items only work if the corresponding non-element forms are also selected.  So you can't get *just* the SVG element, for example, without getting the SVG text as well.  Is that intended?

Does this mean that `svg` should be renamed `svgText`, etc.?

Also, would you consider `svgNode` rather than `svgElement`, since it is shorter?

**Comment by pkra** [comment]
> Is that intended?

Not really. Just a result of being lazy. I will work that in.

> Does this mean that svg should be renamed svgText, etc.?

I'd be happy to find some better names. I just copied those from @zorkow's PR. I could also imagine to have `svg.text` and `svg.node` but I'm not very good at naming things :smile: 

> Also, would you consider svgNode rather than svgElement, since it is shorter?

That sounds good to me.

**Comment by pkra** [comment]
I've updated the branch to address most comments.

What I have not addressed yet is @dpvc's question whether `svg` should become `svgText` . I'm not sure whether that's necessary -- but it's a 3/10 for me so I'm ok with changing it if we decide that. Any thoughts?

**Comment by pkra** [comment]
As per F2F, ready to go.

**Pull request merged**
