### PR TITLE
[main] enable css output without html output

### LINKED ISSUE #292: No css output without html or htmlNode
Extracting this from https://github.com/mathjax/MathJax-node/pull/289#issuecomment-279821382

>  [...] to handle requests for `css` when there is no request for `html` or `htmlNode`.  You may want to move [line 594](https://github.com/mathjax/MathJax-node/blob/f1946b2aee3d3eab96fb5aa13e7e8f7f116fa9a2/lib/main.js#L594) to the top of that function, right before [line 566](https://github.com/mathjax/MathJax-node/blob/f1946b2aee3d3eab96fb5aa13e7e8f7f116fa9a2/lib/main.js#L566).

 If I make the change, the following test still fails.

```javascript
 var tape = require('tape');
var mjAPI = require("../lib/main.js");

tape('CSS output', function(t) {
    t.plan(1);
    mjAPI.start();
    var tex = 'x';
    mjAPI.typeset({
        math: tex,
        format: "TeX",
        css: true
    }, function(data) {
        t.ok(data.css, 'css output while no other output');
    });
});
```
Digging a little bit, `CHTMLSTYLES` is undefined at that point. Maybe it's a restarting issue?

### PR DESCRIPTION
**Pull request by pkra**
Resolves #292

### CODE REVIEW

**Comment by dpvc** [comment]
I think the test should also check if the svg element is produced (one of the two changes relates to that).  I would also say that the tests should also check if *only* the desired properties are produced.  For example `speakText` appears in the `result` whether you have asked for it or not.

**Comment by dpvc** [comment]
Other than that, the PR is good.

**Comment by pkra** [comment]
Thanks! I'll update the test.

**Comment by pkra** [comment]
> I would also say that the tests should also check if only the desired properties are produced. 

That will be covered by #285, correct?

**Comment by dpvc** [comment]
> That will be covered by #285, correct?

It would be if that were implemented, yes.  But no one commented on it, so I was not sure if anyone thought that was a good idea.

**Comment by pkra** [comment]
> But no one commented on it

Copy that. Just added +1.

Also, I've updated the test. PTAL?

**Comment by dpvc** [comment]
OK, looks good.

**Pull request merged**
