### PR TITLE
Update fontURL, support for reconfiguration

### LINKED ISSUE #323: update default fontURL
https://github.com/mathjax/MathJax-node/blob/master/lib/main.js#L41

### PR DESCRIPTION
**Pull request by pkra**
Fixes #323

### CODE REVIEW

**Comment by pkra** [comment]
I ended up going with a simple `replace` in the `config()` method. Not sure if there are objections to that.

@dpvc is there neeed for `config()`to  be synchronized with the queue in general?

**Comment by dpvc** [comment]
I don't think this change should be made.  As mentioned in #323, just as with MathJax in the browser, configuration should be done before any typesetting occurs.  There are many things that can't be reconfigured after typesetting begins; for example, you can't change the extensions after the initial typeset.  I would not complicate the code (and add maintenance costs) for one feature while leaving all the others unaddressed.  Is there really a use case for changing the font url between typesets?  If so, you can always do `mjAPI.start()` again after the reconfiguration.

So I recommend not applying this PR.

**Comment by pkra** [comment]
See my comments on the issue.

**Comment by pkra** [comment]
Closing in favor of #326

**Pull request closed without merging**
