### PR TITLE
Add Tape tests

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by pkra** [comment]
This branch contains the patches from the issue104 branch (since it includes a test for them).

**Comment by pkra** [comment]
Let me re-try this...

**Comment by dpvc** [comment]
I notice that this pull request actually runs the tape tests via travis.  Is that intentional (I don't know anything about travis).  Does that mean that when we pull this, all the tests will be performed for every pull request from now on?  With just these three tests, that is not a problem, but if we start to add tests for MathJax itself, we certainly don't want them all to run every time you look at a pull request.  (Currently, the Selenium-based test suite takes 20-30 minutes to run.)

**Comment by dpvc** [comment]
I also notice that this branch relies on my `issue104` branch and the `iojs` branch.  I have merged the `issue104` branch, but are you planning a pull request for `iojs` separately, or is this it?  I don't ilk merging branches before their dependencies are merged.

**Comment by pkra** [comment]
> I notice that this pull request actually runs the tape tests via travis. Is that intentional?

Yes.

> Does that mean that when we pull this, all the tests will be performed for every pull request from now on? 

Yes. And every push, actually.

> With just these three tests, that is not a problem, but if we start to add tests for MathJax itself, we certainly don't want them all to run every time you look at a pull request. (Currently, the Selenium-based test suite takes 20-30 minutes to run.)

And only for one browser, no?

Anyway, yes, that would be the goal. I don't think it'll be a problem, actually. Let's discuss this at the next F2F.

**Comment by pkra** [comment]
> are you planning a pull request for iojs separately, or is this it? 

Sorry about that.

This merges back into the iojs branch. If we merge iojs first, I could just make another PR to develop.

**Comment by dpvc** [comment]
No problem.  I'll merge `iojs` first and then this one.

**Comment by pkra** [comment]
Thanks!

**Pull request merged**
