### PR TITLE
add test for #220

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by pkra** [comment]
Please squash if you accept this, @dpvc.

**Comment by pkra** [comment]
Any particular reason this was closed instead of squash-merged?

**Comment by dpvc** [comment]
Sorry, I thought I did the merge.  Must have hit the wrong button.

**Comment by pkra** [comment]
Thanks! 

I just noticed that one test run failed -- but it was a Travis problem. Since other test run worked, I think it was just a temporary failure of Travis.

**Comment by dpvc** [comment]
Both tests had passed when I tried to merged earlier, so I'm not sure what the issue was.

**Comment by pkra** [comment]
Travis had trouble initializing so I think everything is fine. Besides, there'll be more runs as we merge this into develop and master.

**Pull request merged**
