### PR TITLE
improve full-width characters rendering

### PR DESCRIPTION
**Pull request by ambar**

### CODE REVIEW

**Comment by pkra** [comment]
Thanks for the PR.

Please note that PRs must be based on the `develop` branch (not master).

You also might want to add some comments on what you are trying to do. (I'm guessing this is for #299?)

**Comment by ambar** [comment]
@pkra rebased!

**Comment by ambar** [comment]
I tried to use Puppeteer(https://github.com/ambar/puptex) before I found this workaround, do you think it's worth?

**Comment by pkra** [comment]
@ambar a fix for #299 would be great (and should have better overall performance than spinning up puppeteer/Chrome). But @dpvc will have to comment on the approach you're taking.

**Comment by ambar** [comment]
@pkra Thanks!

**Comment by dpvc** [comment]
@pkra, I'm OK with the change, if you want to merge it.

**Comment by pkra** [comment]
Thanks. I just haven not got around to it -- the pending bug fix release needs to be wrapped up before we merge.

**Comment by pkra** [comment]
Sorry for taking so long to come back to this.

We're ok with merging as is. 

(We thought about adding an option to customize widths of halfwidth forms but that can be done later.)

**Comment by pkra** [comment]
I'm wondering if we should generalize this using https://github.com/sindresorhus/string-width. I'll make a new issue.

**Pull request merged**
