### PR TITLE
[main] add option for custom path variables

### LINKED ISSUE #134: loading third party extensions
Just a note to think about how users can specify third party extensions (i.e., without copying extensions into the right folder of core MathJax).

### PR DESCRIPTION
**Pull request by pkra**
* add top-level config option
* add test (inclu. test extension)
* update readme
Resolves #134

### CODE REVIEW

**Comment by pkra** [comment]
This should wait until the next feature release.

**Comment by pkra** [comment]
Also, this is only meant as a first draft.

**Comment by pkra** [comment]
I have no idea why the URL test fails on old node versions. I'll look into it.

**Comment by dpvc** [comment]
Looks like a reasonable approach.

**Comment by pkra** [comment]
I believe the failing tests are independent of this issue. 

They seem to be due to MathJax v2.7.3 being installed on old versions of npm which do not support the package lock file (and thus do not stick to 2.7.2).

@dpvc @zorkow is it ok to update the package lock file to MathJax v2.7.3?

**Comment by pkra** [comment]
@zorkow ok'ed this F2F. I'll update the PR.

**Comment by pkra** [comment]
I've also fixed a typo in the Readme.

**Comment by dpvc** [comment]
Your earlier comment indicated this was a first draft.  Are you ready for merging at this point?

**Comment by pkra** [comment]
> Your earlier comment indicated this was a first draft. Are you ready for merging at this point?

I'm ready. I just wasn't sure if that approach is acceptable.

**Pull request merged**
