### PR TITLE
update .travis.yml

### LINKED ISSUE #152: Publish to npm via travis
Let's do that.

### LINKED ISSUE #153: travis: which node versions to test?
Given https://github.com/mathjax/MathJax-node/commit/93ae1a8c834fbab9fa9ac59b7745561ac97e437c#commitcomment-15888948, should we add more versions than `stable`?

### PR DESCRIPTION
**Pull request by pkra**
* extend test coverage of nodejs; fixes #153
* add automatic publishing to npm; fixes #152

### CODE REVIEW

**Comment by pkra** [comment]
Note: we should do a release candidate to check that publishing to npm works in real world conditions.

**Comment by pkra** [comment]
@dpvc do you happen to know why the build on node 4 fails?

**Comment by dpvc** [comment]
I think I've fixed the problem.  Do you know how to get the test to run again (other than making another commit to the branch)?

**Comment by dpvc** [comment]
Apparently closing and opening the PR will re-trigger travis.  I will try that.

**Comment by dpvc** [comment]
That seems to have done it (though the old tests are still showing).  The new ones all passed.

**Comment by pkra** [comment]
@dpvc The tests are still failing. I'm guessing the patch-4 branch holds the fix? If so, I'll merge it into my branch.

**Comment by pkra** [comment]
All clear.

**Comment by pkra** [comment]
@dpvc 

>  Do you know how to get the test to run again (other than making another commit to the branch)?

It's also possible to re-run a test on Travis itself; not sure if you just need to login or if I'd need to give you access.

**Comment by pkra** [comment]
I've updated the npm credentials. I think this is ready to go.

**Pull request merged**
