### PR TITLE
Specifiy batik version

### PR DESCRIPTION
**Pull request by physikerwelt**
The latest version batik 1.8 did not work for me.

### CODE REVIEW

**Comment by physikerwelt** [comment]
I think this patch should land in 0.3.
Batik 1.8 can be tested in the future.
See the error I got for 1,8
(https://gist.github.com/physikerwelt/57b3884fb89b475d1994)

**Comment by pkra** [comment]
Please make PRs against `develop` not `master.

**Comment by pkra** [comment]
FWIW, it seems like the problem is that Batik changed their naming scheme (to `-1.8.jar`) and renaming the files breaks things. If you change mj-single/page to match the file names, things work. Yet another reason for #59...

**Comment by dpvc** [comment]
You can make a symbolic link named `batik-rasterizer.jar` to the `batik-rasterizer-1.8.jar` file, and MathJax-node will find and use that just fine.  Not sure what the Windows version of that is, but this works on Mac OS X, and presumably, Linux

**Pull request closed without merging**
