### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by dpvc**
This PR creates the release version 2.0.2.  The updates include:

* New ability to specify paths for 3rd-party extensions
* Fix to problem with `useFontCache: false` not be applied properly.
* Update to MathJax v2.7.3 and jsdom v11.x.

### CODE REVIEW

**Comment by pkra** [comment]
[semver](https://semver.org/) would say this is 2.1.0 since a feature was added.

**Comment by pkra** [comment]
@dpvc do you have a timeline for this release?

**Comment by dpvc** [comment]
I was away all last week, and have been clearing the decks since I got back.  I will merge this and tag the release shortly.

**Comment by dpvc** [comment]
OK, it's been tagged, and is available on npmjs.com

**Pull request merged**
