### PR TITLE
[main] HTML output: fix manual line-breaks

### LINKED ISSUE #335: [CommonHTML] manual line-breaks not working
Via https://github.com/lwchkg/gitbook-plugin-mathjax-commonhtml/issues/4

Something like `A \\ B` generates something like

```html
<span class="mjx-chtml MJXc-display">
    <span class="mjx-math" style="width: 100%;" aria-label="A \\ B ">
        <span class="mjx-mrow" style="width: 100%;" aria-hidden="true">
            <span class="mjx-stack" style="width: 100%; vertical-align: 0;">
                <span class="mjx-block" style="text-align: center;">
                    <span class="mjx-box">
                        <span class="mjx-mi">
                            <span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.519em; padding-bottom: 0.298em;">A</span>
                        </span>
                        <span class="mjx-mspace" style="width: 0px; height: 0px;"></span>
                        <span class="mjx-mi">
                            <span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.446em; padding-bottom: 0.298em;">B</span>
                        </span>
                    </span>
                </span>
            </span>
        </span>
    </span>
</span>
```

whereas in the browser we get something like

```html
<span class="mjx-chtml MJXc-display">
    <span id="MathJax-Element-4-Frame" class="mjx-full-width mjx-chtml MathJax_CHTML" tabindex="0" style="font-size: 103%; min-width: 0.759em;">
        <span id="MJXc-Node-15" class="mjx-math" style="width: 100%;">
            <span id="MJXc-Node-16" class="mjx-mrow" style="width: 100%;">
                <span class="mjx-stack" style="width: 100%; vertical-align: -1.2em;">
                    <span class="mjx-block" style="text-align: center;">
                        <span class="mjx-box">
                            <span id="MJXc-Node-17" class="mjx-mi">
                                <span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.488em; padding-bottom: 0.306em;">A</span>
                            </span>
                        </span>
                    </span>
                    <span class="mjx-block" style="text-align: center; padding-top: 0.467em;">
                        <span class="mjx-box">
                            <span id="MJXc-Node-18" class="mjx-mspace" style="width: 0px; height: 0px;"></span>
                            <span id="MJXc-Node-19" class="mjx-mi">
                                <span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.488em; padding-bottom: 0.306em;">B</span>
                            </span>
                        </span>
                    </span>
                </span>
            </span>
        </span>
    </span>
</span>
```

### PR DESCRIPTION
**Pull request by pkra**
Resolves #335

### CODE REVIEW

**Comment by pkra** [comment]
As per @dpvc in https://github.com/mathjax/MathJax-node/pull/338#issuecomment-314088338

>  it looks OK.

**Comment by dpvc** [comment]
Still looks OK.

**Comment by dpvc** [comment]
(OOPS, I see you were not waiting for another LGTM).

**Comment by pkra** [comment]
Thanks though!

**Pull request merged**
