### PR TITLE
Prevent the color extension from auto-loading

### LINKED ISSUE #175: Prevent the `color` extension from auto-loading
From https://github.com/mathjax/MathJax-node/issues/143#issuecomment-168243285.

> You are right to point out the `autoload-all` extension, and I was going to say that because `\color` is already defined in MathJax's TeX input jax by default, that `autoload-all` would not redefine it, but I checked the code and I am wrong; `\color` is set to autoload the color extension.  I'm not sure that is the desired behavior for MathJax-node, since that means it will operate differently from default MathJax in the browser.

### PR DESCRIPTION
**Pull request by pkra**
Fixes #175

### CODE REVIEW

**Comment by dpvc** [comment]
I'm wondering if a test that checks the result of something like `\color{red}{x}x` might be worth adding, since with the original `autoload-all`, this would make both x's red, while with the modification, it should only make the first one red.

**Comment by pkra** [comment]
> I'm wondering if a test that checks the result of something like \color{red}{x}x might be worth adding, 

Will do.

**Comment by pkra** [comment]
New test added.

**Comment by pkra** [comment]
ping @dpvc

**Comment by pkra** [comment]
Thanks!

**Pull request merged**
